import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireAdminAuth } from "@/lib/auth";
import { enforceSameOrigin } from "@/lib/request-guards";
import { prismaWriteErrorResponse } from "@/lib/api-helpers";

/**
 * Auto-generate digital catalog from all products & categories.
 * Creates one page per product using its first image, grouped by category.
 * Idempotent: checks for existing auto-generated catalog first.
 */
export async function POST(req: NextRequest) {
  const originDenied = enforceSameOrigin(req);
  if (originDenied) return originDenied;

  const authResult = await requireAdminAuth();
  if (!authResult.ok) return authResult.response;

  try {
    // Get all categories with their subcategories and products
    const categories = await prisma.category.findMany({
      include: {
        translations: true,
        subCategories: {
          include: {
            translations: true,
            products: {
              include: {
                translations: true,
                images: { orderBy: { order: "asc" }, take: 1 },
              },
              orderBy: { order: "asc" },
            },
          },
          orderBy: { order: "asc" },
        },
      },
      orderBy: { order: "asc" },
    });

    // Build pages = each product = one page
    const pages: { imageUrl: string; order: number }[] = [];
    let order = 0;

    for (const cat of categories) {
      for (const sub of cat.subCategories) {
        for (const product of sub.products) {
          const img = product.images[0]?.url;
          if (img) {
            pages.push({ imageUrl: img, order: order++ });
          }
        }
      }
    }

    if (pages.length === 0) {
      return NextResponse.json(
        { error: "No products with images found" },
        { status: 400 },
      );
    }

    // Build translations from category names
    const catTranslations = categories.reduce(
      (acc, cat) => {
        for (const tr of cat.translations) {
          if (!acc[tr.locale]) acc[tr.locale] = [];
          acc[tr.locale].push(tr.name);
        }
        return acc;
      },
      {} as Record<string, string[]>,
    );

    const translations = Object.entries(catTranslations).map(
      ([locale, names]) => ({
        locale,
        title: `Dijital Katalog — ${names.slice(0, 3).join(", ")}`,
      }),
    );

    if (translations.length === 0) {
      translations.push(
        { locale: "tr", title: "Dijital Katalog" },
        { locale: "fr", title: "Catalogue Numérique" },
        { locale: "en", title: "Digital Catalog" },
      );
    }

    // Delete existing auto-generated catalog
    await prisma.digitalCatalog.deleteMany({
      where: { autoGenerated: true },
    });

    const slug = `otomatik-katalog-${Date.now()}`;

    const catalog = await prisma.digitalCatalog.create({
      data: {
        slug,
        published: false,
        autoGenerated: true,
        translations: {
          create: translations,
        },
        pages: {
          create: pages,
        },
      },
      include: {
        translations: true,
        pages: { orderBy: { order: "asc" } },
      },
    });

    return NextResponse.json(catalog, { status: 201 });
  } catch (error) {
    return prismaWriteErrorResponse(error);
  }
}
