"use client";

import { useEffect, useState, useCallback } from "react";
import { useTranslations } from "next-intl";
import Image from "next/image";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Separator } from "@/components/ui/separator";
import {
  Wand2,
  Image as ImageIcon,
  Check,
  X,
  Loader2,
  ExternalLink,
  Package,
  RefreshCw,
} from "lucide-react";

interface CatalogPage {
  imageUrl: string;
  order: number;
}

interface Translation {
  locale: string;
  title: string;
}

interface Catalog {
  id: string;
  slug: string;
  published: boolean;
  autoGenerated: boolean;
  coverImage: string | null;
  translations: Translation[];
  pages: CatalogPage[];
}

export default function AdminDigitalCatalog() {
  const t = useTranslations("adminDigitalCatalog");
  const [catalog, setCatalog] = useState<Catalog | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [publishing, setPublishing] = useState(false);
  const [coverUploading, setCoverUploading] = useState(false);
  const [error, setError] = useState("");

  const fetchCatalog = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/catalog?autoGenerated=true");
      const data = await res.json();
      const cats = Array.isArray(data) ? data : [];
      const auto = cats.find((c: Catalog) => c.autoGenerated);
      setCatalog(auto || null);
    } catch {
      setCatalog(null);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchCatalog();
  }, [fetchCatalog]);

  async function handleGenerate() {
    setGenerating(true);
    setError("");
    try {
      const res = await fetch("/api/digital-catalog/generate", {
        method: "POST",
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Generation failed");
      setCatalog(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Bilinmeyen hata");
    } finally {
      setGenerating(false);
    }
  }

  async function handlePublish() {
    if (!catalog) return;
    setPublishing(true);
    try {
      const res = await fetch(`/api/catalog/${catalog.id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ published: !catalog.published }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setCatalog((prev) =>
        prev ? { ...prev, published: data.published } : prev,
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : "Error");
    } finally {
      setPublishing(false);
    }
  }

  async function handleCoverUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file || !catalog) return;
    setCoverUploading(true);
    try {
      const fd = new FormData();
      fd.append("file", file);
      const upload = await fetch("/api/upload", {
        method: "POST",
        body: fd,
      });
      const uploadData = await upload.json();
      if (!upload.ok) throw new Error(uploadData.error);

      const tempId = uploadData.tempId;
      const publish = await fetch("/api/media/publish", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tempId }),
      });
      const publishData = await publish.json();
      if (!publish.ok) throw new Error(publishData.error);

      const coverUrl = publishData.url;
      const res = await fetch(`/api/catalog/${catalog.id}`, {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ coverImage: coverUrl }),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error);
      setCatalog((prev) =>
        prev ? { ...prev, coverImage: coverUrl } : prev,
      );
    } catch (err) {
      setError(err instanceof Error ? err.message : "Upload failed");
    } finally {
      setCoverUploading(false);
    }
  }

  async function handleRegenerate() {
    if (
      catalog &&
      catalog.pages.length > 0 &&
      !confirm(t("regenerateConfirm"))
    )
      return;
    await handleGenerate();
  }

  if (loading) {
    return (
      <div className="flex min-h-[300px] items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-(--arvesta-gold)" />
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="font-display text-2xl font-semibold text-white">
            {t("title")}
          </h1>
          <p className="text-sm text-(--arvesta-text-muted)">{t("desc")}</p>
        </div>
      </div>

      {error && (
        <div className="rounded-lg border border-red-400/30 bg-red-500/10 px-4 py-3 text-sm text-red-300">
          {error}
        </div>
      )}

      {/* Generate Button */}
      <Card className="border-white/5 bg-(--arvesta-bg-card)">
        <CardContent className="p-6">
          <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <h3 className="font-display text-lg font-semibold text-white">
                {t("autoGenerate")}
              </h3>
              <p className="text-sm text-(--arvesta-text-muted)">
                {t("autoGenerateDesc")}
              </p>
            </div>
            <div className="flex gap-2">
              {catalog && catalog.pages.length > 0 && (
                <Button
                  variant="outline"
                  onClick={handleRegenerate}
                  disabled={generating}
                  className="border-white/10 text-(--arvesta-text-muted)"
                >
                  <RefreshCw
                    className={`mr-2 h-4 w-4 ${generating ? "animate-spin" : ""}`}
                  />
                  {t("regenerate")}
                </Button>
              )}
              <Button
                onClick={handleGenerate}
                disabled={generating}
                className="bg-(--arvesta-accent) hover:bg-(--arvesta-accent-hover)"
              >
                {generating ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Wand2 className="mr-2 h-4 w-4" />
                )}
                {generating ? t("generating") : t("generate")}
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Auto-generated catalog */}
      {catalog && catalog.pages.length > 0 && (
        <>
          <Separator className="bg-white/5" />

          {/* Stats */}
          <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
            <Card className="border-white/5 bg-(--arvesta-bg-card)">
              <CardContent className="p-4 text-center">
                <Package className="mx-auto mb-1 h-5 w-5 text-(--arvesta-gold)" />
                <p className="text-2xl font-bold text-white">
                  {catalog.pages.length}
                </p>
                <p className="text-xs text-(--arvesta-text-muted)">
                  {t("productsCount")}
                </p>
              </CardContent>
            </Card>
            <Card className="border-white/5 bg-(--arvesta-bg-card)">
              <CardContent className="p-4 text-center">
                {catalog.published ? (
                  <Check className="mx-auto mb-1 h-5 w-5 text-emerald-400" />
                ) : (
                  <X className="mx-auto mb-1 h-5 w-5 text-amber-400" />
                )}
                <p className="text-2xl font-bold text-white">
                  {catalog.published ? t("published") : t("draft")}
                </p>
                <p className="text-xs text-(--arvesta-text-muted)">
                  {t("status")}
                </p>
              </CardContent>
            </Card>
          </div>

          {/* Cover Image Upload */}
          <Card className="border-white/5 bg-(--arvesta-bg-card)">
            <CardContent className="p-6">
              <h3 className="mb-4 font-display text-lg font-semibold text-white">
                {t("coverImage")}
              </h3>
              <div className="flex items-start gap-4">
                {catalog.coverImage ? (
                  <div className="relative h-32 w-24 overflow-hidden rounded-lg border border-white/10">
                    <Image
                      src={catalog.coverImage}
                      alt="Cover"
                      fill
                      className="object-cover"
                    />
                    <button
                      type="button"
                      onClick={() => {
                        fetch(`/api/catalog/${catalog.id}`, {
                          method: "PUT",
                          headers: { "Content-Type": "application/json" },
                          body: JSON.stringify({ coverImage: null }),
                        });
                        setCatalog((prev) =>
                          prev ? { ...prev, coverImage: null } : prev,
                        );
                      }}
                      className="absolute right-1 top-1 rounded bg-black/60 p-1 text-white hover:bg-black/80"
                    >
                      <X className="h-3 w-3" />
                    </button>
                  </div>
                ) : null}
                <label className="cursor-pointer">
                  <input
                    type="file"
                    accept="image/*"
                    className="hidden"
                    disabled={coverUploading}
                    onChange={handleCoverUpload}
                  />
                  <div className="flex h-24 w-24 items-center justify-center rounded-lg border-2 border-dashed border-white/20 bg-white/5 hover:bg-white/10">
                    {coverUploading ? (
                      <Loader2 className="h-5 w-5 animate-spin text-(--arvesta-text-muted)" />
                    ) : (
                      <ImageIcon className="h-6 w-6 text-(--arvesta-text-muted)" />
                    )}
                  </div>
                </label>
              </div>
            </CardContent>
          </Card>

          {/* Page Preview Grid */}
          <Card className="border-white/5 bg-(--arvesta-bg-card)">
            <CardContent className="p-6">
              <h3 className="mb-4 font-display text-lg font-semibold text-white">
                {t("preview")}
              </h3>
              <div className="grid grid-cols-3 gap-2 sm:grid-cols-4 md:grid-cols-6">
                {catalog.pages.map((page, i) => (
                  <div
                    key={`${page.imageUrl}-${i}`}
                    className="relative aspect-[3/4] overflow-hidden rounded-lg border border-white/5"
                  >
                    <Image
                      src={page.imageUrl}
                      alt={`Page ${i + 1}`}
                      fill
                      className="object-cover"
                      sizes="120px"
                    />
                    <span className="absolute bottom-1 right-1 rounded bg-black/60 px-1.5 py-0.5 text-[10px] text-white">
                      {i + 1}
                    </span>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>

          {/* Actions */}
          <div className="flex flex-wrap items-center gap-3">
            <span className="mr-2 text-xs text-(--arvesta-text-muted)">
              {t("catalogName")}:{" "}
              {catalog.translations[0]?.title || catalog.slug}
            </span>
            <div className="ml-auto flex gap-2">
              {catalog.id && (
                <a
                  href={`/admin/catalog/preview/${catalog.id}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex shrink-0 items-center justify-center rounded-lg border border-white/10 bg-background hover:bg-muted hover:text-foreground h-8 gap-1.5 px-2.5 text-sm font-medium whitespace-nowrap transition-all"
                >
                  <ExternalLink className="h-4 w-4" />
                  {t("previewCatalog")}
                </a>
              )}
              <Button
                onClick={handlePublish}
                disabled={publishing}
                className={
                  catalog.published
                    ? "border border-amber-400/30 bg-amber-500/10 text-amber-400 hover:bg-amber-500/20"
                    : "bg-(--arvesta-accent) hover:bg-(--arvesta-accent-hover)"
                }
              >
                {publishing ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : catalog.published ? (
                  <X className="mr-2 h-4 w-4" />
                ) : (
                  <Check className="mr-2 h-4 w-4" />
                )}
                {catalog.published ? t("unpublish") : t("publish")}
              </Button>
            </div>
          </div>
        </>
      )}

      {/* Empty state */}
      {!catalog && (
        <Card className="border-white/5 bg-(--arvesta-bg-card)">
          <CardContent className="flex flex-col items-center gap-4 p-12">
            <Package className="h-12 w-12 text-(--arvesta-text-muted)" />
            <p className="text-(--arvesta-text-muted)">{t("noCatalog")}</p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
